name: platica_say
description: "Traductor de voz local en tiempo real para llamadas y conversaciones."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  ffi: ^2.1.3
  intl: ^0.20.2
  archive: ^3.6.1
  crypto: ^3.0.5
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
